services:
  store.api:
    image: storeapi
    build:
      context: .
      dockerfile: Store.Api/Dockerfile
    ports:
      - "${STOREAPI_PORT}:${STOREAPI_PORT}"
      - 8001:8001
    env_file:
      - ../.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - storeapi-data:/app/Data
      - ./Store.Api/ocelot.json:/app/ocelot.json
    depends_on:
      - productservice
      - inventoryservice
    networks:
      - shared-network

volumes:
  storeapi-data:

networks:
  shared-network:
    external: true

