services:
  store.api:
    image: storeapi
    build:
      context: .
      dockerfile: Store.Api/Dockerfile
    ports:
      - "${STOREAPI_PORT}:${STOREAPI_PORT}"
      - "${STOREAPI_PORTALT}:${STOREAPI_PORTALT}"
    env_file:
      - ../.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - storeapi-data:/app/Data
    networks:
      - shared-network

volumes:
  storeapi-data:

networks:
  shared-network:
    external: true

